#!/bin/bash
############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################
set -x
set -e

########## Variables

olddir=~/dotfiles_old             # old dotfiles backup directory
herbst=.config/herbstluftwm/autostart
files=".vimrc .zshrc.d/herman.zsh .Xresources .tmux.conf .gdbinit .config/i3/config .config/rofi/config.rasi \
       $herbst .config/keepmenu/config.ini"

##########

# create dotfiles_old in homedir
mkdir -p "$olddir"
cd "$dir"

function backup_and_link() {
    repo=$1
    destDir=$2
    backup=$3
    shift 2
    files="$*"

    for file in $files; do
        dest="$destDir/${file}"
        if [ -f "$dest" ]; then
            mv "$dest" "${backup}/"
        fi
        if [ -h "$dest" ]; then
            rm "$dest"
        fi
        mkdir -p $(dirname "$dest")
        ln -s "$repo/$file" "$dest"
    done
}

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
backup_and_link ~/dotfiles ~ "$olddir" $files
chmod +x ~/"$herbst"

# utility scripts
scripts="run_replace grab_window.bash grab_window_hlwm.bash"
backup_and_link ~/dotfiles/bin ~/bin "$olddir" $scripts
