#!/bin/bash
############################
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################
set -x
set -e

########## Variables

dir=~/dotfiles                    # dotfiles directory
olddir=~/dotfiles_old             # old dotfiles backup directory
files="vimrc zshrc.d/zshrc Xresources tmux.conf gdbinit config/i3/config config/rofi/config.rasi config/herbstluftwm/autostart"    # list of files/folders to symlink in homedir

##########
mkdir -p ~/.config

# create dotfiles_old in homedir
echo "Creating $olddir for backup of any existing dotfiles in ~"
mkdir -p "$olddir"
echo "...done"

# change to the dotfiles directory
echo "Changing to the $dir directory"
cd "$dir"
echo "...done"

# move any existing dotfiles in homedir to dotfiles_old directory, then create symlinks 
for file in $files; do
    dest=~/".${file}"
    if [ -f "$dest" ]; then
        mv "$dest" "${olddir}/"
    fi
    mkdir -p $(dirname "$dest")
    ln -s "$dir/$file" "$dest"
done

# utility scripts
scripts="run_replace grab_window.bash"
mkdir -p ~/bin
for script in $scripts;do
    ln -s bin/"$script" ~/bin/"$script"
done

cd "$DIR"
