#!/bin/bash

OLDDIR=`pwd`

mkdir -p ~/.vim/autoload ~/.vim/bundle && \

cd ~/.vim/autoload
wget https://tpo.pe/pathogen.vim

cd ~/.vim/bundle
git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/fholgado/minibufexpl.vim.git 
git clone https://github.com/scrooloose/nerdtree
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/vimwiki/vimwiki.git
git clone https://github.com/suan/vim-instant-markdown.git
git clone https://github.com/vim-pandoc/vim-pandoc.git
git clone https://github.com/drmingdrmer/xptemplate.git

cd $OLDDIR
